ALTER TABLE orders ADD COLUMN version bigint NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN created_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE orders ADD COLUMN last_modified_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE invoices ADD COLUMN version bigint NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN created_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE invoices ADD COLUMN last_modified_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE payments ADD COLUMN version bigint NOT NULL DEFAULT 0;
ALTER TABLE payments ADD COLUMN created_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE payments ADD COLUMN last_modified_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
